### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by dasad1564112** [horizon3ai/vcenter_saml_login#12]
Hello, my Python encoding has been UTF-8, but still exploding such a mistake, my Data.mdb file has 1GB. It can be unspeakable when I solve the old MDB before I can solve it.

python3 vcenter_saml_login.py -t xx.xx.xx.xx -p data.mdb
[*] Successfully extracted the IdP certificate
Traceback (most recent call last):
  File "/vcenter_saml_login.py", line 342, in <module>
    trusted_cert_1, domain = get_trusted_cert1(bin_stream, args.verbose)
  File "/vcenter_saml_login.py", line 168, in get_trusted_cert1
    cn = stream.read(f'bytes:{cn_len}').decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 139: invalid start byte

**Comment by Gs52jrfnxnPXBGAW** [comment]
how to solve?
