### ISSUE TITLE
[-] Failed signing the SAML assertion ('Could not deserialize key data')

### ISSUE THREAD

**Issue by corsch** [horizon3ai/vcenter_saml_login#18]
Did anyone else have issues with "Failed signing the SAML assertion"?

```
python3 vcenter_saml_login.py -p data.mdb -t <IP>  -v
[*] Extracted IdP certificate:
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----

[*] Successfully extracted the IdP certificate
[!] Looking for cert 1 at position: 69734592
[!] CN end position: 69735640
[*] CN: cn=TrustedCertChain-1,cn=TrustedCertificateChains,cn=<DOMAIN>.<DOMAIN>,cn=Tenants,cn=IdentityManager,cn=Seces,dc=<DOMAIN>,dc=<DOMAIN>
[*] Domain: <DOMAIN>.<DOMAIN>
[!] Cert 1 size: 999
[*] Extracted Trusted certificate:
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

[*] Successfully extracted trusted certificate 1
Cert 2 Size: 1053
[*] Extracted Trusted certificate:
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

[*] Successfully extracted trusted certificate 2
[*] Obtaining hostname from vCenter SSL certificate
[*] Found hostname <FQDN> for <IP>
[*] Initiating SAML request with <IP>
[*] Generating SAML assertion
[*] Signing the SAML assertion
[-] Failed signing the SAML assertion
Traceback (most recent call last):
  File "<PATH>/Log4jCenter/utils/vcenter_saml_login/vcenter_saml_login.py", line 349, in <module>
    s = sign_assertion(t, trusted_cert_1, trusted_cert_2, idp_cert)
  File "<PATH>/Log4jCenter/utils/vcenter_saml_login/vcenter_saml_login.py", line 281, in sign_assertion
    signed_assertion = signer.sign(root, reference_uri=assertion_id, key=key, cert=[cert1, cert2])
  File "/usr/local/lib/python3.9/dist-packages/signxml/__init__.py", line 398, in sign
    key = load_pem_private_key(ensure_bytes(key), password=passphrase, backend=default_backend())
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/primitives/serialization/base.py", line 22, in d_pem_private_key
    return ossl.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 823, in loadm_private_key
    return self._load_key(
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1070, in _lokey
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1129, in _hae_key_loading_error
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an upported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrithText(code=218529960, lib=13, reason=168, reason_text=b'error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wr tag'), _OpenSSLErrorWithText(code=218546234, lib=13, reason=58, reason_text=b'error:0D06C03A:asn1 encoding routinasn1_d2i_ex_primitive:nested asn1 error'), _OpenSSLErrorWithText(code=218640442, lib=13, reason=58, reason_text=b'or:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error'), _OpenSSLErrorWithText(code=1514987 lib=9, reason=13, reason_text=b'error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib')])

```

I get the same error when trying to "check" the key with openssl:

```
 openssl rsa -in private.key -check    
   
unable to load Private Key
139866836145536:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../crypto/asn1/tasn_dec.c:1149:
139866836145536:error:0D06C03A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error:../crypto/asn1/tasn_dec.c:713:
139866836145536:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:646:Field=version, Type=PKCS8_PRIV_KEY_INFO
139866836145536:error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:../crypto/pem/pem_pkey.c:88:
```

**Comment by corsch** [comment]
Issue is fixed in https://github.com/horizon3ai/vcenter_saml_login/pull/16
