### ISSUE TITLE
Failed logging in with SAML request.(expected 302 redirect)

### ISSUE THREAD

**Issue by kingz40o** [horizon3ai/vcenter_saml_login#19]
Any idea what could have gone wrong?
Ver: VMware VirtualCenter 7.0.2 build-17920168
`[-] Failed logging in with SAML request
Traceback (most recent call last):
  File "/Users/vcenter_saml_login.py", line 351, in <module>
    c = login(args.target, s)
  File "/Users/vcenter_saml_login.py", line 301, in login
    raise Exception("expected 302 redirect")
Exception: expected 302 redirect`
Response:
`[400] An error occurred while processing the authentication response from the vCenter Single Sign-On server. Details: HTTP error code: 403, status: BadResponse, sub status: Issuer not trusted: .`

**Comment by kingz40o** [comment]
I found something wrong.
The reason is HOSTNAME mismatch.
Target: sub.domain.com
Original results : 
`[*] Found hostname *.domain.com for sub.domain.com`
After modification(success): 
`[*] Found hostname sub.domain.com for sub.domain.com`
