### ISSUE TITLE
Exception: expected 302 redirect

### ISSUE THREAD

**Issue by Blackh4n** [horizon3ai/vcenter_saml_login#8]
Hello,

I keep getting this error and have no clue why is that.

```
[*] Successfully extracted the IdP certificate
[*] CN: cn=TrustedCertChain-1,cn=TrustedCertificateChains,cn=<redacted>.local,cn=Tenants,cn=IdentityManager,cn=Services,dc=<redacted>,dc=local
[*] Domain: <redacted>.local
[*] Successfully extracted trusted certificate 1
[*] Successfully extracted trusted certificate 2
[*] Obtaining hostname from vCenter SSL certificate
[*] Found hostname <redacted>.<redacted>.local for <redacted>
[*] Initiating SAML request with <redacted>
[-] Failed initiating SAML request with <redacted>
Traceback (most recent call last):
  File "/home/morpheus/stuff/vcenter_saml_login/vcenter_saml_login.py", line 347, in <module>
    req = saml_request(args.target)
  File "/home/morpheus/stuff/vcenter_saml_login/vcenter_saml_login.py", line 241, in saml_request
    raise Exception("expected 302 redirect")
Exception: expected 302 redirect
```

I did check a little bit and if I understand correctly, the code expects to 302 redirect and gives exception when it doesn't. The thing is, the host is making 302 redirect but still, I'm getting this exception. Any help, suggestions will be priceless. Thanks.

**Comment by Blackh4n** [comment]
Hello again,

After a little digging, I saw the "login" function response me as 400, not 302. So that's the problem. Maybe it's because of the version difference, IDK. The version I'm trying with is VMware vCenter Server 7.0.3

**Comment by scopedsecurity** [comment]
The stack trace you have provided shows that the saml_request() call which requests https://\<HOSTNAME>\/ui/login. When you browse manually to that host at that URL, what do you see? It should be a 302 redirect to https://\<HOSTNAME\>/websso/SAML2/SSO/<VCENTER DOMAIN>

**Comment by Blackh4n** [comment]
Hey,

Yes, it does redirect me to there when I browse manually. Here is a screenshot.
![vcenter](https://user-images.githubusercontent.com/43624420/148503980-fce1d419-3543-4bfc-ad61-199d745063fc.PNG)

But when I debug the python script, It seems the script gets "400 bad request" before the error. This print comes from inside of the "login" function and before the exception you put. ("iki" string in the screenshot is my indicator for debugging)
![vcenter2](https://user-images.githubusercontent.com/43624420/148504583-cb3faaf8-4ba5-4cbb-8c80-609001c26ca1.PNG)

**Comment by scopedsecurity** [comment]
When you browse manually, does the redirected URL exactly match the URL that the script is attempting to reach? As in does the domain after SAML2/SSO/ match?

**Comment by Blackh4n** [comment]
Yes, it does match, they are the same URL. So I think the problem is the data trying to send. It's trying to send POST data which is "SAMLRequest=". But when I browse manually, it's a get request and I don't know exactly the details of data, maybe there is another problem inside the data, idk. I did debug, it's generating a big XML but I didn't go further.

**Comment by scopedsecurity** [comment]
It's hard to say where the issue may be, but if you are able to compare a manual valid login request XML to the XML payload that the script sends it could help you debug further any issues. In the function fill_template() is where the script will insert parsed data into the XML template generate a SAML request. If you compare those to the manual maybe it will help?

**Comment by scopedsecurity** [comment]
Thanks for all the info. I'll dig into a 7.0.3 when I have some time to dig into this some more.

**Comment by barrett092** [comment]
Getting this 302 redirect error as well. Just wanted to check if anyone has figured out a fix.

**Comment by sm00v** [comment]
Alright got some information for ya. Version 7.0.3 has a different XML request that I was able to get my hands on. I didn't have the time or energy to port your tool but maybe with this XML body you can do some porting for >=7.0.3.

New request body:
```
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response Destination="https://10.1.1.118/ui/saml/websso/sso" ID="_ad1bbc361015e5330f5a42c0a1f6105b" InResponseTo="_e8aee5bbe34165bf5e0bc45b39e89247" IssueInstant="2023-08-31T23:05:00.677Z" Version="2.0"
	xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
	<saml2:Issuer
		xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://contosovcenter.contoso.lan/websso/SAML2/Metadata/vsphere.local

	</saml2:Issuer>
	<saml2p:Status>
		<saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
		<saml2p:StatusMessage>Request successful</saml2p:StatusMessage>
	</saml2p:Status>
	<saml2:Assertion ID="_0602d62b-5765-4f8a-a1a9-6a0d272783ff" IssueInstant="2023-08-31T23:05:00.651Z" Version="2.0"
		xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
		<saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://contosovcenter.contoso.lan/websso/SAML2/Metadata/vsphere.local</saml2:Issuer>
		<ds:Signature
			xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
			<ds:SignedInfo>
				<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
				<ds:Reference URI="#_0602d62b-5765-4f8a-a1a9-6a0d272783ff">
					<ds:Transforms>
						<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
						<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
							<ec:InclusiveNamespaces PrefixList="xsd xsi"
								xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/>
							</ds:Transform>
						</ds:Transforms>
						<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
						<ds:DigestValue>NAMDus6OHrRrfe5hXvpAkO8I5/s7ng6Wn0xQ9Y=</ds:DigestValue>
					</ds:Reference>
				</ds:SignedInfo>
				<ds:SignatureValue>qkShak6Q949q/vUXuo8+YZx6btrPzdMzDQMVMiqkvk3AsqgRKC5USVXY/oW8yZUHx96Zc5WudlCNaoSFWhVXuWrxWxMsf/Aldd+rHDL6NiBHR4HULcNk3vNSNcnDqHDcetoFnXSJkuySCuTjGueRLDQbEmAPv/3wGJO2Auv5eWV6YTON2KyzJWRWkuzec1YN5iyLqKv1kolkmtmm5kK/iDt/KAUZ6+90Je1OzG1+J2nH7CvHBlREggtSd8RgI2oPfubIf33e2ZfKnwH8Xfa+fsWShdxmTZSmFBPj65/7iWu4ViBVYXoL3hbXiMNKM1CAomeqHV5g==</ds:SignatureValue>
				<ds:KeyInfo>
					<ds:X509Data>
						<ds:X509Certificate>MiiaR0g/C7zMA0GCSqGSIb3DQEBCwUAMIGiMQswCQYDVQQDDAJDQTEXMBUGCgmSJomT8ixkARkWB3ZzcGhlcmUxFTATBgoJkiaJk/IsZAEZFgVsb2NhbDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExJDAiBgNVBAoMG21pZHZjZW50ZXIubWlkbGFuZHBvd2VyLmxhbjEbMBkGA1UECwwSVk13YXJlIEVuZ2luZWVyaW5nMB4XDTIyMTIyMTE0NTczOFoXDTMyMTIxNTE1MDY1MFowGDEWMBQGA1UEAwwNc3Nvc2VydmVyU2lnbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANG1L2oW5Bywn6mdE+hIaDqtHIGr1L4hSe0ZX6c7vBWR6LM/550l72/+hJ9S2wwYuuxN+3Uu90oUedRReSMhrmG9ZR5FF7ndJvCmKmJ18o/U7Dnkn4VxV+r17WNDs4LV/M3J5m/FMhnYF4VboFo8HxqbpQkThHo8r++1JlVKkqNv1BR2uktSckvrg/xTCJJlLqn0jnsGz2iIDmeR0qr9wS1rL64BFVz/A0ldO+ulDU+CwhHDOu0iPcGS3FFeouMu7cb8ck6nlaJg0Yz7YIPNUQhzCGoqBNtYvLaprY4+MC/1v7j2dseID9293m6VFh7br7Q4CZN47u4DZeRy9gMG3rMCAwEAAaOBxTCBwjALBgNVHQ8EBAMCBeAwJgYDVR0RBB8wHYIbbWlkdmNlbnRlci5taWRsYW5kcG93ZXIubGFuMB0GA1UdDgQWBBQutCVz9vafqUTGGz+wgZpphegzNDAfBgNVHSMEGDAWgBRlOjeKalRvt39t72Bgb1z3Aj7GBzBLBggrBgEFBQcBAQQ/MD0wOwYIKwYBBQUHMAKGL2h0dHBzOi8vbWlkdmNlbnRlci5taWRsYW5kcG93ZXIubGFuL2FmZC92ZWNzL2NhMA0GCSqGSIb3DQEBCwUAA4IBAQDNtRxKXLXS/eFsG1I5NltOKZF5X0hP0+zHe0BF2MVDi0vg/K9XYT7xg2uODhRFmYk6TntAHQ47kZ0cNNOjfithVd1dtFW+xMB5OHS9vF8tqYdJWFAdTFzP38d+puBmMYFjJVNqLm8XMSs31OsRhU8+7VvCjQHZLJxKFdO9cNf5MXU0v9/hkWA7Rud1lAYfrUzSl6VehoFJptlN5nC089s5BTbq3Flijh+pqhwYj85HoDMR2Ej9LK34C7D5p4dvUHReBm6rJQchhGrIZXF0NUebospONEsXXYgG1/GX8yq70AGdx21ScxYDNCcjEbOi299dQdCEq5J+uZSTpk0jjOZK</ds:X509Certificate>
						<ds:X509Certificate>MA0GCSqGSIb3DQEBCwUAMIGiMQswCQYDVQQDDAJDQTEXMBUGCgmSJomT8ixkARkWB3ZzcGhlcmUxFTATBgoJkiaJk/IsZAEZFgVsb2NhbDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExJDAiBgNVBAoMG21pZHZjZW50ZXIubWlkbGFuZHBvd2VyLmxhbjEbMBkGA1UECwwSVk13YXJlIEVuZ2luZWVyaW5nMB4XDTIyMTIxODE1MDY1MFoXDTMyMTIxNTE1MDY1MFowgaIxCzAJBgNVBAMMAkNBMRcwFQYKCZImiZPyLGQBGRYHdnNwaGVyZTEVMBMGCgmSJomT8ixkARkWBWxvY2FsMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEkMCIGA1UECgwbbWlkdmNlbnRlci5taWRsYW5kcG93ZXIubGFuMRswGQYDVQQLDBJWTXdhcmUgRW5naW5lZXJpbmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDpQacC6fMMXlf5LdzJlHuAhA4r656bTnpiS+YKO9k7Cm9akOGj9PR/ZUT659pXrHXoVw1Xppv0WGoQvGUjX1Dp5RR2pIiF11kUTLTHiea4Gwrqa4jiZcpVgBfpMem98abP4/FHLUeLMvyRSMMJd0A7SdPGFffmup8GziQi2PVRPOgfBf6Zk9M1FUrIulUKHBdceyd+PZGAYUD5bsdyb31uJPr6uBJIUdBaODIQ8ThSUO7WWymeVzy+O8vMwxCxBddPSPzz+zNMB2JjUipZPZwa5UpaHpaOlR/bQ0AT5CkUe9qHMheohirsvVIV5xeNg75IUc023rGZul5lcH4E7bphAgMBAAGjZjBkMB0GA1UdDgQWBBRlOjeKalRvt39t72Bgb1z3Aj7GBzAfBgNVHREEGDAWgQ5lbWFpbEBhY21lLmNvbYcEfwAAATAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADANBgkqhkiG9w0BAQsFAAOCAQEAqy6tShve3wvh+79h4jTqKGqvTnqgfbFSmc6E6WkPJd/uw1MiPUtAQkEX91GpJYh7hYO1GxIN0jwZBmA5LEHgvSlZUTs0Ju973jNmbWmyy9altkQKxam8Irjx6jZ4EiyGWsI1BLQSa2eZ5VDeL1FwjG6ny6MPSpRY1qag9E3vKVvtGHuSEMTAErpseOrHsgMRKY4TVBfj2u6ZHDp1KgiUgRiSxhShYGG9QwHLxgs+RTsEnkBUB184nFHecjOlNs2MQR1FfB06ll8wO18iEfQEjHU0DAsixQ2dRpuZSEKKs3T+i9UbNY2FW2mbbtioUzjnrpACHnO0Nx1cMcaKD7aq0A==</ds:X509Certificate>
					</ds:X509Data>
				</ds:KeyInfo>
			</ds:Signature>
			<saml2:Subject>
				<saml2:NameID Format="http://schemas.xmlsoap.org/claims/UPN">Administrator@VSPHERE.LOCAL</saml2:NameID>
				<saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
					<saml2:SubjectConfirmationData InResponseTo="_e8aee5bbe34165bf5e0bc45b39e89247" NotOnOrAfter="2023-08-31T23:08:45.645Z" Recipient="https://10.1.1.118/ui/saml/websso/sso"/>
				</saml2:SubjectConfirmation>
			</saml2:Subject>
			<saml2:Conditions NotBefore="2023-08-31T23:03:45.645Z" NotOnOrAfter="2023-08-31T23:08:45.645Z">
				<saml2:ProxyRestriction Count="10"/>
				<saml2:Condition Count="10"
					xmlns:rsa="http://www.rsa.com/names/2009/12/std-ext/SAML2.0" xsi:type="rsa:RenewRestrictionType"/>
					<saml2:AudienceRestriction>
						<saml2:Audience>https://10.1.1.118/ui/saml/websso/metadata</saml2:Audience>
					</saml2:AudienceRestriction>
				</saml2:Conditions>
				<saml2:AuthnStatement AuthnInstant="2023-08-31T23:05:00.645Z" SessionIndex="_fe7f40c519d92840eed5f1f405774aa0" SessionNotOnOrAfter="2023-09-01T07:05:00.644Z">
					<saml2:AuthnContext>
						<saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml2:AuthnContextClassRef>
					</saml2:AuthnContext>
				</saml2:AuthnStatement>
				<saml2:AttributeStatement>
					<saml2:Attribute FriendlyName="userPrincipalName" Name="http://schemas.xmlsoap.org/claims/UPN" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xsd:string">Administrator@VSPHERE.LOCAL</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute FriendlyName="Groups" Name="http://rsa.com/schemas/attr-names/2009/01/GroupIdentity" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xsd:string">vsphere.local\Users</saml2:AttributeValue>
						<saml2:AttributeValue xsi:type="xsd:string">vsphere.local\Administrators</saml2:AttributeValue>
						<saml2:AttributeValue xsi:type="xsd:string">vsphere.local\CAAdmins</saml2:AttributeValue>
						<saml2:AttributeValue xsi:type="xsd:string">vsphere.local\SystemConfiguration.Administrators</saml2:AttributeValue>
						<saml2:AttributeValue xsi:type="xsd:string">vsphere.local\SystemConfiguration.BashShellAdministrators</saml2:AttributeValue>
						<saml2:AttributeValue xsi:type="xsd:string">vsphere.local\SystemConfiguration.ReadOnly</saml2:AttributeValue>
						<saml2:AttributeValue xsi:type="xsd:string">vsphere.local\SystemConfiguration.SupportUsers</saml2:AttributeValue>
						<saml2:AttributeValue xsi:type="xsd:string">vsphere.local\LicenseService.Administrators</saml2:AttributeValue>
						<saml2:AttributeValue xsi:type="xsd:string">vsphere.local\Everyone</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute FriendlyName="givenName" Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xsd:string">Administrator</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute FriendlyName="Subject Type" Name="http://vmware.com/schemas/attr-names/2011/07/isSolution" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xsd:string">false</saml2:AttributeValue>
					</saml2:Attribute>
					<saml2:Attribute FriendlyName="surname" Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
						<saml2:AttributeValue xsi:type="xsd:string">vsphere.local</saml2:AttributeValue>
					</saml2:Attribute>
				</saml2:AttributeStatement>
			</saml2:Assertion>
		</saml2p:Response>
```
